# Generated by Django 5.2.7 on 2025-10-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_is_active'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_time'], name='flights_fli_departu_5bc2af_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['price'], name='flights_fli_price_59fecb_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['company'], name='flights_fli_company_6b27ed_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['origin'], name='flights_fli_origin_9948b6_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['destination'], name='flights_fli_destina_4db167_idx'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(condition=models.Q(('available_seats__gte', 0)), name='flight_available_seats_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(condition=models.Q(('total_seats__gte', 0)), name='flight_total_seats_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='flight_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(condition=models.Q(('available_seats__lte', models.F('total_seats'))), name='flight_available_le_total'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.UniqueConstraint(fields=('company', 'flight_number', 'departure_time'), name='uniq_company_flightnumber_departuretime'),
        ),
    ]
